c_compiler:            # [win]
- vs2019               # [win]
cxx_compiler:          # [win]
- vs2019               # [win]

c_compiler:         # [osx]
  - clang_bootstrap # [osx]
cxx_compiler:       # [osx]
  - clang_bootstrap # [osx]
